### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by nntoan** [CaptainHookPhp/GrumPHP#1]
Can you please add your captainhook.json and your grumphp.yaml as an example?

Thanks,

**Comment by heiglandreas** [comment]
By default after installation via `composer require captainhook/grumphp` everything should be setup and ready to run.

**Comment by heiglandreas** [comment]
I've just added the content of the `captainhook. json` that should have been installed to the README. Does that help you?

**Comment by nntoan** [comment]
Thank you!
