### ISSUE TITLE
Plan to make it compatible with CaptainHook v5 ?

### ISSUE THREAD

**Issue by Ig0r-M-magic42** [CaptainHookPhp/GrumPHP#2]
Latest version of this repo does not work with CaptainHook v5 due to constraint in composer.json https://github.com/CaptainHookPhp/GrumPHP/blob/7f40a58084bbe7d77b9f3cb9538dd3773769bcfa/composer.json#L21 file.

Are there plans to update this extension ? Will it work if constraint is updated ?

**Comment by Ig0r-M-magic42** [comment]
and grum PHP

**Comment by Ig0r-M-magic42** [comment]
**Note** https://github.com/CaptainHookPhp/GrumPHP/pull/3 has been raised for now, planning to test this and see if it's working

**Comment by sebastianfeldmann** [comment]
Uhh good point, wasn't on my radar until now

**Comment by sebastianfeldmann** [comment]
I tagged a new version `0.2.0` with your changes.

Thanks again for reporting the issue and much more so for the pull request.
